<?php

declare(strict_types=1);

namespace App\Application\Actions\Tournament;

use App\Application\Action\ApiAction;
use App\Application\Responder\JsonResponder;
use App\Application\Service\CreateAdSlotService;
use App\Domain\Role\TournamentUserRoleRepository;
use App\Domain\Shared\Exception\ValidationException;
use App\Domain\Shared\Slug;
use App\Domain\Sport\SportRepository;
use App\Domain\Tournament\TournamentRepository;
use App\Domain\User\User;
use Psr\Http\Message\ResponseInterface as Response;

/**
 * POST /api/v1/tournaments  (authenticated)
 * Any authenticated user can create a tournament and becomes its organizer.
 * Points/periods are seeded from the sport's default_config. A unique slug is
 * autogenerated from the name. Default per-tournament ad slots (header,
 * between_matches, footer) are also seeded — each with its default WhatsApp
 * banner — so the public layout has saleable space from day one.
 */
final class CreateTournamentAction extends ApiAction
{
    /**
     * Placements seeded for every new tournament. Mirrors the layout the public
     * site actually renders. Each is created active via CreateAdSlotService,
     * which also inserts the slot's default "espacio disponible" banner.
     *
     * @var array<int,array{placement:string,name:string}>
     */
    private const DEFAULT_AD_SLOTS = [
        ['placement' => 'header', 'name' => 'Header torneo'],
        ['placement' => 'between_matches', 'name' => 'Entre partidos'],
        ['placement' => 'footer', 'name' => 'Footer torneo'],
    ];

    public function __construct(
        JsonResponder $responder,
        private TournamentRepository $tournaments,
        private TournamentUserRoleRepository $roles,
        private SportRepository $sports,
        private CreateAdSlotService $adSlots
    ) {
        parent::__construct($responder);
    }

    protected function handle(): Response
    {
        /** @var User $user */
        $user = $this->request->getAttribute('user');

        $body = $this->body();

        $name        = trim((string) ($body['name'] ?? ''));
        $sportId     = isset($body['sport_id']) ? (int) $body['sport_id'] : 0;
        $description = isset($body['description']) ? trim((string) $body['description']) : null;
        $logoUrl     = isset($body['logo_url']) ? trim((string) $body['logo_url']) : null;
        $startsAt    = isset($body['starts_at']) && $body['starts_at'] !== '' ? (string) $body['starts_at'] : null;
        $timezone    = isset($body['timezone']) && $body['timezone'] !== ''
            ? (string) $body['timezone']
            : 'America/Bogota';

        $errors = [];
        if ($name === '') {
            $errors['name'] = 'El nombre del torneo es obligatorio.';
        }
        if ($sportId <= 0) {
            $errors['sport_id'] = 'Debes seleccionar un deporte.';
        }
        if ($startsAt !== null && !$this->isValidDate($startsAt)) {
            $errors['starts_at'] = 'La fecha de inicio no es válida (formato YYYY-MM-DD).';
        }
        if ($errors !== []) {
            throw new ValidationException($errors);
        }

        $sport = $this->sports->findById($sportId);
        if ($sport === null) {
            throw new ValidationException(['sport_id' => 'El deporte seleccionado no existe.']);
        }

        $config = $sport->defaultConfig ?? [];
        $periods    = (int) ($config['periods'] ?? 2);
        $pointsWin  = (int) ($config['points_win'] ?? 3);
        $pointsDraw = (int) ($config['points_draw'] ?? 1);
        $pointsLoss = (int) ($config['points_loss'] ?? 0);

        // Shareable, human-readable slug: "<nombre>-<mes>-<año>" (e.g.
        // "liga-espana-junio-2026"). The organizer can regenerate/change it
        // later if it gets spammed. Made unique with a numeric suffix.
        $slug = $this->uniqueSlug($name . '-' . $this->monthYearSuffix());

        $tournament = $this->tournaments->create([
            'sport_id'                => $sport->id,
            'owner_user_id'           => $user->id,
            'name'                    => $name,
            'slug'                    => $slug,
            'description'             => $description !== '' ? $description : null,
            'logo_url'                => $logoUrl !== '' ? $logoUrl : null,
            // No draft mode: tournaments start accepting registrations.
            'status'                  => 'registration',
            // Private by default — reachable only via the shareable link.
            'is_public'               => false,
            'periods_count'           => $periods,
            'points_win'              => $pointsWin,
            'points_draw'             => $pointsDraw,
            'points_loss'             => $pointsLoss,
            'allow_late_registration' => !empty($body['allow_late_registration']),
            // Registrations open by default, with a code ready for the share link.
            'registration_open'       => true,
            'registration_code'       => $this->uniqueRegistrationCode(),
            'starts_at'               => $startsAt,
            'timezone'                => $timezone,
        ]);

        // The creator becomes the organizer of this tournament.
        $this->roles->create($tournament->id, $user->id, 'organizer', null);

        // Seed default per-tournament ad slots (+ their default banners) via the
        // service so the public layout has saleable space immediately. This
        // action is non-transactional (tournament + role are committed above), so
        // seeding is defensively isolated: a failure here must NEVER abort an
        // otherwise-successful tournament creation. CreateAdSlotService wraps each
        // slot+banner in its own transaction, so a partial seed cannot leave a
        // slot without its default creative.
        $this->seedDefaultAdSlots($tournament->id);

        return $this->responder->created($this->response, $tournament);
    }

    /**
     * Best-effort seeding of the default ad slots for a freshly created
     * tournament. Swallows and logs any error so tournament creation succeeds
     * regardless. Only ever called on creation — never on update.
     */
    private function seedDefaultAdSlots(int $tournamentId): void
    {
        foreach (self::DEFAULT_AD_SLOTS as $slot) {
            try {
                $this->adSlots->create([
                    'tournament_id' => $tournamentId,
                    'placement'     => $slot['placement'],
                    'name'          => $slot['name'],
                    'is_active'     => true,
                ]);
            } catch (\Throwable $e) {
                error_log(sprintf(
                    'Default ad slot seeding failed (tournament %d, placement %s): %s',
                    $tournamentId,
                    $slot['placement'],
                    $e->getMessage()
                ));
            }
        }
    }

    private function uniqueSlug(string $name): string
    {
        $base = Slug::make($name);
        $slug = $base;
        $suffix = 1;

        while ($this->tournaments->slugExists($slug)) {
            $suffix++;
            $slug = $base . '-' . $suffix;
        }

        return $slug;
    }

    /**
     * Spanish month + year suffix for the shareable slug (e.g. "junio-2026").
     */
    private function monthYearSuffix(): string
    {
        static $months = [
            1 => 'enero', 2 => 'febrero', 3 => 'marzo', 4 => 'abril',
            5 => 'mayo', 6 => 'junio', 7 => 'julio', 8 => 'agosto',
            9 => 'septiembre', 10 => 'octubre', 11 => 'noviembre', 12 => 'diciembre',
        ];

        $now = new \DateTimeImmutable('now');

        return $months[(int) $now->format('n')] . '-' . $now->format('Y');
    }

    private function uniqueRegistrationCode(): string
    {
        do {
            $code = Slug::code(8);
        } while ($this->tournaments->registrationCodeExists($code));

        return $code;
    }

    private function isValidDate(string $date): bool
    {
        $d = \DateTime::createFromFormat('Y-m-d', $date);

        return $d !== false && $d->format('Y-m-d') === $date;
    }
}
