<?php

declare(strict_types=1);

namespace App\Application\Actions\Tournament;

use App\Application\Action\ApiAction;
use App\Application\Responder\JsonResponder;
use App\Domain\Role\TournamentUserRoleRepository;
use App\Domain\Shared\Exception\ValidationException;
use App\Domain\Shared\Slug;
use App\Domain\Sport\SportRepository;
use App\Domain\Tournament\TournamentRepository;
use App\Domain\User\User;
use Psr\Http\Message\ResponseInterface as Response;

/**
 * POST /api/v1/tournaments  (authenticated)
 * Any authenticated user can create a tournament and becomes its organizer.
 * Points/periods are seeded from the sport's default_config. A unique slug is
 * autogenerated from the name.
 */
final class CreateTournamentAction extends ApiAction
{
    public function __construct(
        JsonResponder $responder,
        private TournamentRepository $tournaments,
        private TournamentUserRoleRepository $roles,
        private SportRepository $sports
    ) {
        parent::__construct($responder);
    }

    protected function handle(): Response
    {
        /** @var User $user */
        $user = $this->request->getAttribute('user');

        $body = $this->body();

        $name        = trim((string) ($body['name'] ?? ''));
        $sportId     = isset($body['sport_id']) ? (int) $body['sport_id'] : 0;
        $description = isset($body['description']) ? trim((string) $body['description']) : null;
        $logoUrl     = isset($body['logo_url']) ? trim((string) $body['logo_url']) : null;
        $startsAt    = isset($body['starts_at']) && $body['starts_at'] !== '' ? (string) $body['starts_at'] : null;
        $timezone    = isset($body['timezone']) && $body['timezone'] !== ''
            ? (string) $body['timezone']
            : 'America/Bogota';

        $errors = [];
        if ($name === '') {
            $errors['name'] = 'El nombre del torneo es obligatorio.';
        }
        if ($sportId <= 0) {
            $errors['sport_id'] = 'Debes seleccionar un deporte.';
        }
        if ($startsAt !== null && !$this->isValidDate($startsAt)) {
            $errors['starts_at'] = 'La fecha de inicio no es válida (formato YYYY-MM-DD).';
        }
        if ($errors !== []) {
            throw new ValidationException($errors);
        }

        $sport = $this->sports->findById($sportId);
        if ($sport === null) {
            throw new ValidationException(['sport_id' => 'El deporte seleccionado no existe.']);
        }

        $config = $sport->defaultConfig ?? [];
        $periods    = (int) ($config['periods'] ?? 2);
        $pointsWin  = (int) ($config['points_win'] ?? 3);
        $pointsDraw = (int) ($config['points_draw'] ?? 1);
        $pointsLoss = (int) ($config['points_loss'] ?? 0);

        $slug = $this->uniqueSlug($name);

        $tournament = $this->tournaments->create([
            'sport_id'                => $sport->id,
            'owner_user_id'           => $user->id,
            'name'                    => $name,
            'slug'                    => $slug,
            'description'             => $description !== '' ? $description : null,
            'logo_url'                => $logoUrl !== '' ? $logoUrl : null,
            'status'                  => 'draft',
            'periods_count'           => $periods,
            'points_win'              => $pointsWin,
            'points_draw'             => $pointsDraw,
            'points_loss'             => $pointsLoss,
            'allow_late_registration' => !empty($body['allow_late_registration']),
            'registration_open'       => false,
            'registration_code'       => null,
            'starts_at'               => $startsAt,
            'timezone'                => $timezone,
        ]);

        // The creator becomes the organizer of this tournament.
        $this->roles->create($tournament->id, $user->id, 'organizer', null);

        return $this->responder->created($this->response, $tournament);
    }

    private function uniqueSlug(string $name): string
    {
        $base = Slug::make($name);
        $slug = $base;
        $suffix = 1;

        while ($this->tournaments->slugExists($slug)) {
            $suffix++;
            $slug = $base . '-' . $suffix;
        }

        return $slug;
    }

    private function isValidDate(string $date): bool
    {
        $d = \DateTime::createFromFormat('Y-m-d', $date);

        return $d !== false && $d->format('Y-m-d') === $date;
    }
}
